spring.application.name=franchise-management
spring.r2dbc.url=r2dbc:postgresql://neondb_owner:npg_4y3gwUsPkVnp@ep-holy-fog-amac2a7c.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.r2dbc.username=user
spring.r2dbc.password=password
spring.h2.console.enabled=true
spring.sql.init.mode=always
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.use-root-path=false
springdoc.api-docs.path=/v3/api-docs
springdoc.packages-to-scan=com.accenture.franchisemanagement.infrastructure.adapters.inbound
springdoc.swagger-ui.url=/v3/api-docs
springdoc.swagger-ui.configUrl=/v3/api-docs/swagger-config
springdoc.swagger-ui.config-url=/v3/api-docs/swagger-config
springdoc.swagger-ui.layout=BaseLayout